import React from 'react';
import { Container, Card, CardContent, CardMedia, Typography, Button, Box } from '@mui/material';
import { useNavigate } from 'react-router-dom';

// Import local images
import technicalQuizImage from '../assets/images/360_F_569964847_Wa3tNpPYRGABpplPGSFT3LLB7E2wU0jb.webp';
import ticTacToeImage from '../assets/images/tic-tac-toe-set-on-yellow-background-flat-lay.webp';
import towerOfHanoiImage from '../assets/images/ChatGPT Image Apr 22, 2025, 11_01_13 AM.png';
import wordScrambleImage from '../assets/images/word-scramble.svg';

const games = [
  {
    id: 'technical-quiz',
    title: 'Technical Quiz',
    description: 'Test your knowledge',
    image: technicalQuizImage,
    path: '/games/technical-quiz'
  },
  {
    id: 'tic-tac-toe',
    title: 'Tic Tac Toe',
    description: 'Classic game with a strategic twist',
    image: ticTacToeImage,
    path: '/games/tic-tac-toe'
  },
  {
    id: 'tower-of-hanoi',
    title: 'Tower of Hanoi',
    description: 'Test your problem-solving skills',
    image: towerOfHanoiImage,
    path: '/games/tower-of-hanoi'
  },
  {
    id: 'word-scramble',
    title: 'Word Scramble',
    description: 'Unscramble words generated by AI',
    image: wordScrambleImage,
    path: '/games/word-scramble'
  }
];

const Games = () => {
  const navigate = useNavigate();

  return (
    <Container maxWidth="lg">
      <Box sx={{ mt: 4, mb: 4 }}>
        <Typography 
          variant="h3" 
          component="h1" 
          align="center" 
          sx={{ fontFamily: '"Comic Sans MS", cursive, sans-serif', color: '#ff4081', mb: 4 }}
        >
          🎮 Select Games 🎮
        </Typography>

        <Box
          sx={{
            display: 'grid',
            gridTemplateColumns: { xs: '1fr', sm: 'repeat(2, 1fr)', md: 'repeat(3, 1fr)' },
            gap: 4
          }}
        >
          {games.map((game) => (
            <Card
              key={game.id}
              sx={{
                height: '100%',
                display: 'flex',
                flexDirection: 'column',
                transition: 'transform 0.3s, box-shadow 0.3s',
                cursor: 'pointer',
                boxShadow: 3,
                borderRadius: 4,
                '&:hover': {
                  transform: 'scale(1.05)',
                  boxShadow: 6,
                  backgroundColor: '#fffaf0'
                }
              }}
              onClick={() => navigate(game.path)}
            >
              <CardMedia
                component="img"
                height="200"
                image={game.image}
                alt={game.title}
                sx={{ borderTopLeftRadius: 16, borderTopRightRadius: 16 }}
              />
              <CardContent sx={{ flexGrow: 1, textAlign: 'center' }}>
                <Typography variant="h5" component="h2" sx={{ color: '#4a148c', fontWeight: 'bold' }}>
                  {game.title}
                </Typography>
                <Typography sx={{ color: '#616161', mb: 2 }}>
                  {game.description}
                </Typography>
                <Button
                  variant="contained"
                  sx={{
                    backgroundColor: '#ff9800',
                    fontWeight: 'bold',
                    color: '#fff',
                    '&:hover': {
                      backgroundColor: '#fb8c00'
                    },
                    borderRadius: 8
                  }}
                >
                  🎯 Play Now
                </Button>
              </CardContent>
            </Card>
          ))}
        </Box>
      </Box>
    </Container>
  );
};

export default Games;
